### ISSUE TITLE
The settings Menu isn't opening and other issues I had/complaints? (idk how to put them)

### ISSUE THREAD

**Issue by Whynotreally** [megaminerjenny/HeavenStudio#107]
I couldn't open up the menu for the editor settings and theme no matter what I tried (button and command for it) Idk if it's me or some other thing but I couldn't get them to open. The other problems I had were having to restart the song all the way from the start and there's controls or editor menu to open so I can't figure if I could start from a specific point. Maybe a simple request of get some color changes some of the other games like it has for karate man

**Comment by minenice55** [comment]
settings menu is currently unimplemented
