### ISSUE TITLE
Application not opening on MacOS 10.15.7

### ISSUE THREAD

**Issue by NetzIGuess** [megaminerjenny/HeavenStudio#112]
I'm wondering if this is because it just doesn't run on catalina or if it's a problem.

**Comment by Saraistupid** [comment]
It's a problem with Unity games downloaded from the internet and running on Mac, even if you get it running, you can't open the file browser for some reason, so it's basically in an unusable state

**Comment by Jorish1and2and** [comment]
How do I get to use it?

**Comment by DashyDesu** [comment]
having the same issue,, hopefully the mac version will be updated to fix this soon... i hope.

**Comment by ThatZeoMan** [comment]
We are currently discussing ways to add mac compatibility, although it may not come for a while. In the meantime, try ways of running windows apps on mac, such as Parallels Desktop or Wine (i think, ive never used wine lol).

**Comment by Saraistupid** [comment]
> Wine (i think, ive never used wine lol).
Wine isn't an option at all (Wine on anything that isn't Linux works worse than it is on Linux)

For M1 users I recommend using a Linux VM for now if you need a free method, follow this vid [right here](https://www.youtube.com/watch?v=BVrxyszJ37I)
I'd still recommend Parallels but that's paid

If you use an Intel Mac, honestly, just sell that and get a windows laptop.
