### ISSUE TITLE
Music is not importing (windows 64 standalone)

### ISSUE THREAD

**Issue by MemeyWasTaken** [megaminerjenny/HeavenStudio#119]
I tried importing music but it would not play! I tried changing to .mp3 .wav .ogg, re-installing, restarting the game, restarting my computer, and nothing. Checking the music file alone comes out fine music playing and everything. Does anyone have a fix? (I am on windows 11 sadly, so it could be that)

**Comment by Starpelly** [comment]
The music file could be corrupted, have you tried other files?

**Comment by ThatZeoMan** [comment]
It appears this is an issue with Windows 11, I have found an identical issue also on Windows 11. All Windows 10 users do not have this problem, at least from what I can tell.

**Comment by RebatemanYT** [comment]
Wait... did you upgrade from Win10 or fresh install of Win11? When I was using Win11, it worked fine and others in the discord say it works for them on Win11...

**Comment by Saraistupid** [comment]
Can you get a log file?
If you don't know how to here's a step by step guide:
> Getting the log of Heaven Studio:
> - Close Heaven Studio (to get a fresh log file)
> - Re-Open Heaven Studio
> - Play until you experience your bug
> - Close Heaven Studio
> - If you are on Windows go to `%USERPROFILE%\AppData\LocalLow\Megaminerzero\Heaven Studio\`
> - If you are on Linux go to `~/.config/unity3d/Megaminerzero/Heaven Studio/`
> - If you are on MacOS go to `~/Library/Logs/Megaminerzero/Heaven Studio`
> - Send the Player.log file from that directory here

**Comment by arklypurple** [comment]
also having this issue on windows 10

**Comment by ThatZeoMan** [comment]
again, could you send a log file?

> Getting the log of Heaven Studio:
> 
> - Close Heaven Studio (to get a fresh log file)
> - Re-Open Heaven Studio
> - Play until you experience your bug
> - Close Heaven Studio
> - If you are on Windows go to %USERPROFILE%\AppData\LocalLow\Megaminerzero\Heaven Studio\
> - If you are on Linux go to ~/.config/unity3d/Megaminerzero/Heaven Studio/
> - If you are on MacOS go to ~/Library/Logs/Megaminerzero/Heaven Studio
> - Send the Player.log file from that directory here

**Comment by minenice55** [comment]
getting no helpful responses that would narrow down this issue, closing...
if anyone else gets this issue please provide log files (a core dump would be even better!)
