### ISSUE TITLE
Controls

### ISSUE THREAD

**Issue by GhostNovaaa** [megaminerjenny/HeavenStudio#174]
what are the controls on keyboard?

**Comment by ThaCuber** [comment]
z and x

**Comment by blank3times** [comment]
I see occasional references to copy and paste if I'm not mistaken, is there actually that feature?

**Comment by Starpelly** [comment]
I'll use this thread to bump the idea that you all should switch to the new Input System.

**Comment by ThaCuber** [comment]
@Starpelly the what

**Comment by GhostNovaaa** [comment]
What new input system

**Comment by GhostNovaaa** [comment]
> I'll use this thread to bump the idea that you all should switch to the new Input System.

What new input system

**Comment by ThatZeoMan** [comment]
> I see occasional references to copy and paste if I'm not mistaken, is there actually that feature?

Hold Alt before dragging a selection of cues

**Comment by blank3times** [comment]
Thank you, that helps a ton.
