### ISSUE TITLE
dj school permanant mark

### ISSUE THREAD

**Issue by dirt-bee** [megaminerjenny/HeavenStudio#176]
if you put a "scratch-o!" and switch game on the input, it puts a scratching image permanantly.
![bug1](https://user-images.githubusercontent.com/115891182/195998705-3dd9d456-002c-45c1-9b39-bb550d4ac63d.png)
![bug2](https://user-images.githubusercontent.com/115891182/195998778-c9fdba36-24ff-4510-86c0-0d598e28db8e.png)

**Comment by blank3times** [comment]
Hurrah!
