### ISSUE TITLE
No game activity (MacOS)

### ISSUE THREAD

**Issue by LeWolfYT** [megaminerjenny/HeavenStudio#187]
The Z and X keys don't work for any games, and for most of them the events don't do anything. Karate Joe is pink.

**Comment by minenice55** [comment]
mac is known to misbehave and we frankly need help in addressing this

**Comment by ThatZeoMan** [comment]
> The Z and X keys don't work for any games, and for most of them the events don't do anything. Karate Joe is pink.

If i may ask, what computer and version of macos are you using? Where did you downooad/compile heaven studio mac?

**Comment by LeWolfYT** [comment]
I'm running Macos Monterey on a MacBook Pro Intel.


Sent from my Apple Watch

**Comment by Saraistupid** [comment]
You may just install windows on a seperate partition for now since you have an intel mac

**Comment by LeWolfYT** [comment]
I don’t have enough storage for it

**Comment by ThatZeoMan** [comment]
> I'm running Macos Monterey on a MacBook Pro Intel.
> […](#)

It’d still like to ask where you got the Heaven Studio program. In my experience, the prebuilt binary hasn’t worked for me, and compiling it myself had loads of issues. Did you download the prebuilt binary from the main GitHub page, did you compile it yourself with Unity, or did you get it sing other way?

**Comment by Saraistupid** [comment]
This has been fixed.
