### ISSUE TITLE
GitHub Actions CI

### ISSUE THREAD

**Issue by huantianad** [megaminerjenny/HeavenStudio#2]
Thoughts on using GitHub Actions to build the project? That'll allow for automatic standalone builds for the latest commits, so people can more easily try it out.

I can setup a quick example action later today if that seems useful.

**Comment by fancythedeveloper** [comment]
Looks like someone bothered themselves to actually do it.
https://github.com/Saraistupid/HeavenStudio

**Comment by huantianad** [comment]
@fancythedeveloper no need to be passive agreeable about it. Besides it's the same code as my PR which was referenced right above your comment. It'll be merged whenever @megaminerjenny decides to, just be patient.

**Comment by Saraistupid** [comment]
> Looks like someone bothered themselves to actually do it. https://github.com/Saraistupid/HeavenStudio

I just did what huantianad did in my own repo because Unity was crashing for me and i really needed a Linux build.

**Comment by megaminerjenny** [comment]
Merged huantian's PR. This should be good now.
