### ISSUE TITLE
the exe file wont work

### ISSUE THREAD

**Issue by iwanaeatadonut** [megaminerjenny/HeavenStudio#232]
it just wont work
![image](https://user-images.githubusercontent.com/123442815/214226487-5e3a85b4-87f7-4339-891a-27ee80bbacd2.png)
i have a image that is proof

**Comment by blank3times** [comment]
Have you extracted all the assets and other stuff?

**Comment by iwanaeatadonut** [comment]
> Have you extracted all the assets and other stuff?

Yes i have i dont know what is causing this issue

**Comment by iwanaeatadonut** [comment]
> > Have you extracted all the assets and other stuff?
> 
> Yes i have i dont know what is causing this issue

i did not mean to do that

**Comment by iwanaeatadonut** [comment]
i am still confused about this

**Comment by Starpelly** [comment]
What you're seeing on the screen is what the editor looks like when nothing is loaded.

This is possibly a script error, send your log file located at:
```
C:\Users\[yourname]\AppData\LocalLow\Megaminerzero\Heaven Studio
```

**Comment by Saraistupid** [comment]
Hello! Please try these steps first:

- Re-Download Heaven Studio from here: https://nightly.link/megaminerjenny/HeavenStudio/workflows/windows/master/StandaloneWindows64-build.zip
- Disable any antivirus you have turned on, Heaven Studio is not signed so it may get detected as a "virus" by some antiviruses for that reason.
- Make sure you extract Heaven Studio correctly using the File Explorer's built-in extraction tool or an external tool such as 7-Zip (Recommended).

If none of that work, please grab a log file so we can look into it even more:

#### Getting the log of Heaven Studio:
- Close Heaven Studio (to get a fresh log file)
- Re-Open Heaven Studio
- Play until you experience your bug
 - Close Heaven Studio
- If you are on Windows, Press WIN (Windows Key on your keyboard) + R then put this in the window that'll appear `%USERPROFILE%\AppData\LocalLow\Megaminerzero\Heaven Studio\` then press enter
- Post the Player.log file from that directory here

**Comment by iwanaeatadonut** [comment]
i still need to tell you people something

it work on all the previous versions

**Comment by iwanaeatadonut** [comment]
> What you're seeing on the screen is what the editor looks like when nothing is loaded.
> 
> This is possibly a script error, send your log file located at:
> 
> ```
> C:\Users\[yourname]\AppData\LocalLow\Megaminerzero\Heaven Studio
> ```

i do not know how to open that

**Comment by iwanaeatadonut** [comment]
> 

I FIGURED OUT HOW TO DO THAT

HERE ARE BOTH THE FILES
[Player.log](https://github.com/megaminerjenny/HeavenStudio/files/10495264/Player.log)
[Player-prev.log](https://github.com/megaminerjenny/HeavenStudio/files/10495265/Player-prev.log)

**Comment by iwanaeatadonut** [comment]
ok it seems to work now

**Comment by iwanaeatadonut** [comment]
ok so it only works if i redownload the file
