### ISSUE TITLE
Tempo Change and Music Volume tool problem

### ISSUE THREAD

**Issue by Spiral2839** [megaminerjenny/HeavenStudio#61]
I need help for adding tempo and music because some features needs to be fixed.

**Compare**

Heaven Studio [adding extra tempo didn't work]:
![Capture (8)](https://user-images.githubusercontent.com/40846617/160183729-ca37792c-540b-464a-adc4-759bd1f5ada7.PNG)

Polyrhythm Mania:
![Capture (9)](https://user-images.githubusercontent.com/40846617/160183989-5a9907a9-4490-49e6-92bf-93d2f4969d39.PNG)

**Comment by patataofcourse** [comment]
Tempo changes currently can't be added

**Comment by Saraistupid** [comment]
The tempo change tool was disabled in https://github.com/megaminerjenny/HeavenStudio/commit/ca158363e4cad0e22de07cec9ae2d445931900c8 because the tempo change function was broken and buggy, it'll be re-enabled later when the issues are fixed as far as i know.

**Comment by megaminerjenny** [comment]
Cleaning stuff up and yeah shit don't work. The tools will be re-enabled when they're functional again.
