### ISSUE TITLE
Editor Timeline stuck [up to beat 320+]

### ISSUE THREAD

**Issue by Spiral2839** [megaminerjenny/HeavenStudio#67]
a little help for the problem? idk why...
https://user-images.githubusercontent.com/40846617/160769417-df3a965c-c841-4c6d-b3df-7365cd785d8b.mp4

Screenshot:
![Capture (10)](https://user-images.githubusercontent.com/40846617/160770050-5305ae08-a1cf-4ebe-b816-6a6ab7822432.PNG)

**Comment by Saraistupid** [comment]
This was fixed by @megaminerjenny in a previous week old (i think?) commit, are you sure the song is long enough? do you have the right bpm set?

**Comment by Spiral2839** [comment]
yeah, the song is long than short one.
but I actually use 160 bpm btw.

**Comment by megaminerjenny** [comment]
This should be fixed??? Closing this unless ppl keep running into this somehow.
