### ISSUE TITLE
Music not Playing

### ISSUE THREAD

**Issue by Myst1c0raL** [megaminerjenny/HeavenStudio#72]
Whenever I open a new game, the music doesn't play. When I click on the "change music" tab, nothing happens. And yes, my volume was at 100%

**Comment by Saraistupid** [comment]
are you on Linux?

**Comment by Myst1c0raL** [comment]
No, I’m on MacOS (M1 specifically)

**Comment by Saraistupid** [comment]
Ah, MacOS hasn't been tested, being on M1 is probably the reason, do you mind sharing a log file after selecting a song or opening a remix with a song in it? (The player.log file which can be found in `~/Library/Logs/Megaminerzero/Heaven Studio`)
Remember to do these steps while taking the log file:
- Close Heaven Studio (to get a fresh log file)
- Re-open
- Play until you experience your bug (in your case, selecting a song)
- Close Heaven Studio
- Go to the logs directory and find Player.log
- Attach it here

It would be really nice if you join the discord server for easier communication

**Comment by Myst1c0raL** [comment]
Ah, i would, but I deleted it and unity due to storage constraints on my computer 😕
Sorry about that

**Comment by Saraistupid** [comment]
It would be great if you provide a log file when you have it installed again, you can always grab a build from the github actions (though these are NOT tested at all, because in my understanding you are building the player yourself)

**Comment by Saraistupid** [comment]
Can you try again now? After a bunch of testing of my own, https://github.com/megaminerjenny/HeavenStudio/commit/002fa1997117f9a7b69500598df39a5b8ef724e0 fixed the issue.
