### ISSUE TITLE
Segmentation Fault when running Linux prebuilt binary

### ISSUE THREAD

**Issue by devsydungo** [megaminerjenny/HeavenStudio#82]
Can't run the prebuilt binary for Linux. When trying to run the binary, a window shows briefly with icon then terminal says
`Segmentation fault (core dumped)`
![image](https://user-images.githubusercontent.com/29827612/169627139-cd1080a5-6164-4b4f-8045-e671bc894d5f.png)

This is my device's info if it helps
![image](https://user-images.githubusercontent.com/29827612/169627187-89ce7e42-8e43-4c07-be11-86ca3a299703.png)

Thank you

**Comment by Starpelly** [comment]
[This may help you](https://forum.unity.com/threads/segmentation-fault-core-dumped-in-standalone-app-but-not-in-editor.1226610/)
