### ISSUE TITLE
Not an issue but more of a suggestion

### ISSUE THREAD

**Issue by Explodingcr** [megaminerjenny/HeavenStudio#94]
Would it be possible to add an import feature for Rhythm Heaven Remix Editor files? I've made quite a few remixes with that before finding this and it would be cool if I could import those into HeavenStudio.

**Comment by Starpelly** [comment]
This would require functionality to convert all rhre3 data to hs data.
As rhre3 files are just fancy zip files, it shouldn't be that hard. Obviously there are problems concerning games which are not included in HS yet.

If your question is "is it possible?", than yes.
Although I don't think it will be implemented anytime soon.

**Comment by Saraistupid** [comment]
It's possible, but not really worth the effort
